import type { MessageTemplate } from './index';

/**
 * Pre-legal notice templates for South African property management.
 * These templates contain legally accurate language per the Rental Housing Act,
 * Consumer Protection Act (CPA), and Prevention of Illegal Eviction (PIE) Act.
 */
export const noticeTemplates: Record<string, MessageTemplate> = {
  section8_7day_notice: {
    name: 'section8_7day_notice',
    category: 'UTILITY',
    language: 'en_ZA',
    components: [
      {
        type: 'HEADER',
        format: 'TEXT',
        text: 'NOTICE OF BREACH — Section 8(1) Rental Housing Act',
      },
      {
        type: 'BODY',
        text: [
          'Dear {{1}},',
          '',
          'NOTICE OF BREACH IN TERMS OF SECTION 8(1) OF THE RENTAL HOUSING ACT 50 OF 1999',
          '',
          'Property: {{2}}, Unit {{3}}',
          'Lease Agreement dated: {{4}}',
          '',
          'You are hereby notified that you are in breach of your lease agreement by reason of non-payment of rental.',
          '',
          'Outstanding amount: R{{5}}',
          'Period in arrears: {{6}}',
          '',
          'In terms of Section 8(1) of the Rental Housing Act, you are required to remedy this breach within 7 (seven) calendar days of receipt of this notice, failing which the landlord reserves the right to cancel the lease agreement and institute proceedings for your eviction in terms of the Prevention of Illegal Eviction from and Unlawful Occupation of Land Act 19 of 1998 (PIE Act).',
          '',
          'Compliance deadline: {{7}}',
          '',
          'Payment must be made to:',
          'Account holder: {{8}}',
          'Bank: {{9}}',
          'Account number: {{10}}',
          'Reference: {{11}}',
          '',
          'Should you wish to discuss this matter, please contact the managing agent.',
          '',
          'This notice is served without prejudice to any rights the landlord may have in law.',
        ].join('\n'),
      },
      {
        type: 'FOOTER',
        text: 'ProPassure Property Management — This is a legal notice',
      },
      {
        type: 'BUTTONS',
        buttons: [
          { type: 'QUICK_REPLY', text: 'Arrange Payment' },
          { type: 'QUICK_REPLY', text: 'Dispute Notice' },
          { type: 'QUICK_REPLY', text: 'Contact Agent' },
        ],
      },
    ],
    variables: [
      'tenant_name',
      'property_address',
      'unit_number',
      'lease_date',
      'amount_owed',
      'arrears_period',
      'compliance_deadline',
      'account_holder',
      'bank_name',
      'account_number',
      'payment_reference',
    ],
  },

  section8_20day_notice: {
    name: 'section8_20day_notice',
    category: 'UTILITY',
    language: 'en_ZA',
    components: [
      {
        type: 'HEADER',
        format: 'TEXT',
        text: 'NOTICE — Section 8(1)(a) Consumer Protection Act',
      },
      {
        type: 'BODY',
        text: [
          'Dear {{1}},',
          '',
          'NOTICE OF BREACH IN TERMS OF SECTION 8(1)(a) READ WITH SECTION 14 OF THE CONSUMER PROTECTION ACT 68 OF 2008',
          '',
          'Property: {{2}}, Unit {{3}}',
          'Lease Agreement dated: {{4}}',
          '',
          'You are hereby placed on notice that you are in material breach of the above lease agreement as a result of your failure to pay rental as follows:',
          '',
          'Outstanding amount: R{{5}}',
          'Period in arrears: {{6}}',
          '',
          'In terms of Section 14(2)(b)(i)(bb) of the Consumer Protection Act, read with Regulation 5(1), you are granted 20 (twenty) business days from the date of receipt of this notice to remedy the breach.',
          '',
          'Compliance deadline: {{7}}',
          '',
          'Should you fail to remedy the breach within the stipulated period, the landlord will be entitled to cancel the lease agreement in terms of Section 14(2)(b)(i)(cc) of the CPA, and thereafter institute proceedings for your eviction.',
          '',
          'Please note that the cancellation of the lease does not extinguish your liability for any arrear rental, damages, or costs.',
          '',
          'Payment details:',
          'Account holder: {{8}}',
          'Bank: {{9}}',
          'Account number: {{10}}',
          'Reference: {{11}}',
        ].join('\n'),
      },
      {
        type: 'FOOTER',
        text: 'ProPassure Property Management — This is a legal notice',
      },
      {
        type: 'BUTTONS',
        buttons: [
          { type: 'QUICK_REPLY', text: 'Arrange Payment' },
          { type: 'QUICK_REPLY', text: 'Dispute Notice' },
          { type: 'QUICK_REPLY', text: 'Contact Agent' },
        ],
      },
    ],
    variables: [
      'tenant_name',
      'property_address',
      'unit_number',
      'lease_date',
      'amount_owed',
      'arrears_period',
      'compliance_deadline',
      'account_holder',
      'bank_name',
      'account_number',
      'payment_reference',
    ],
  },

  eviction_notice: {
    name: 'eviction_notice',
    category: 'UTILITY',
    language: 'en_ZA',
    components: [
      {
        type: 'HEADER',
        format: 'TEXT',
        text: 'NOTICE — Eviction Proceedings',
      },
      {
        type: 'BODY',
        text: [
          'Dear {{1}},',
          '',
          'NOTICE OF INTENTION TO INSTITUTE EVICTION PROCEEDINGS',
          'In terms of Section 4 of the Prevention of Illegal Eviction from and Unlawful Occupation of Land Act 19 of 1998 (PIE Act)',
          '',
          'Property: {{2}}, Unit {{3}}',
          '',
          'You are hereby notified that, having failed to remedy the breach of your lease agreement as set out in the notice dated {{4}}, the landlord intends to apply to the Magistrate\'s Court/High Court for an order for your eviction.',
          '',
          'In terms of Section 4(2) of the PIE Act, you are advised that:',
          '1. You have the right to appear before the court on the date of the hearing.',
          '2. You have the right to legal representation.',
          '3. You may apply for legal aid from Legal Aid South Africa.',
          '4. The court will consider all relevant circumstances, including whether alternative accommodation is available.',
          '',
          'Court date: {{5}}',
          'Court: {{6}}',
          'Case number: {{7}}',
          '',
          'We strongly advise you to seek legal advice immediately. Legal Aid South Africa can be reached at 0800 110 110.',
        ].join('\n'),
      },
      {
        type: 'FOOTER',
        text: 'ProPassure Property Management — This is a legal notice',
      },
      {
        type: 'BUTTONS',
        buttons: [
          { type: 'QUICK_REPLY', text: 'Contact Agent' },
          { type: 'QUICK_REPLY', text: 'Request Legal Aid Info' },
        ],
      },
    ],
    variables: [
      'tenant_name',
      'property_address',
      'unit_number',
      'prior_notice_date',
      'court_date',
      'court_name',
      'case_number',
    ],
  },
};
